### ISSUE TITLE
sensor not found on windows.

### ISSUE THREAD

**Issue by antithing** [withrobot/myAHRS_plus#1]
Hi, I just purchased a myAHRS+ sensor, I have plugged it into windows, and the yellow light flashes. But I cannot connect to the sensor. The monitor programme does not find it, and the COM port is not coming up on my machine. DO I need a driver?

Windows 7, 64 bit.

Thank you!

**Comment by antithing** [comment]
Solved. This driver:

http://microco.sm/out/xJs

**Comment by mcajkovs** [comment]
Hello, I have similar problem but on windows 10. Can you please elaborate how do you get the driver? I'm a bit afraid to install software from unknown sources. Thanks
